version: "3"

services:
  node1:
    image: simpleblockchain
    entrypoint: java -jar ./app/SimpleBlockchain.jar
    command: http://node1 http://node2 http://node3 1

  node2:
    image: simpleblockchain
    entrypoint: java -jar ./app/SimpleBlockchain.jar
    command: http://node2 http://node1 http://node3 2

  node3:
    image: simpleblockchain
    entrypoint: java -jar ./app/SimpleBlockchain.jar
    command: http://node3 http://node2 http://node1 3