version: "3"

services:
  node1:
    build:
      context: .
    ports:
      - "8081:8081"
    entrypoint: java -jar ./app/SimpleBlockchain-1.0.jar
    command: 8081 http://node1 http://node2:8082 http://node3:8083 1

  node2:
    build:
      context: .
    ports:
      - "8082:8082"
    entrypoint: java -jar ./app/SimpleBlockchain-1.0.jar
    command: 8082 http://node2 http://node1:8081 http://node3:8083 2

  node3:
    build:
      context: .
    ports:
      - "8083:8083"
    entrypoint: java -jar ./app/SimpleBlockchain-1.0.jar
    command: 8083 http://node3 http://node2:8082 http://node1:8081 3